### ISSUE TITLE
Question : How to optimize Actor's read-write storage?

### ISSUE THREAD

**Issue by i3oi3o** [orbit/orbit#275]
I'm currently working on a game.

I have the in-game item inventory use case which requires frequency read-write.

StorageExtension writes actor's state as one item/document on a database which consumes a lot of I/O if we consider the size of player's inventory.

So, my plan is writing custom read-write which put each in-game item as item/document on the separate table.

```
class PlayerActor extends AbstractActor<PlayerActor.State> implement Player
{
      public static class State
      {
            /** player's other information
            .
            .**/

           @JsonIgnore
           public PlayerInventory playerInventory;
      }

      @Override
      public Task<Void> writeState()
      {
            MyDBExtension mydbExtension = runtime.getFirstExtension(MyDBExtension.class);
            await(state().playerInventory.write(mydbExtension));
            return super.writeState();
      }

      @Override
      public Task<Boolean> readState()
      {
           State playerState = state();
           if(playerState.playerInventory == null)
           {
               playerState.playerInventory = new PlayerInventory("TableName", getIdentiy());
           }
           
           MyDBExtension mydbExtension = runtime.getFirstExtension(MyDB);
           await(playerState.playerInventory.read(mydbExtension));
           return super.readState();
      }
}

```

Here, My optimization questions.
1. Should I lock my custom read-write to make this thread-safe? I see comment in the source code that write/readState() is Asynchronous.
2. Is this the recommended pattern?

Here, My enhancement question.
1. If Orbit designed interface to handle custom read-write and conversion between old State, would this be a good idea?

**Comment by JoeHegarty** [comment]
It's not unusual for users of Orbit to not use the Orbit state system and do something custom, in fact we do this on several internal projects so going that route is fine if it makes sense for your use case.

For your optimization questions:
1. Assuming you wait on the write/read, such as returning it from your method. Then there is no need to lock because the orbit threading guarantees mean no other thread will touch the actor.
For example: `Task setBalance(Integer balance) { state().balance = balance; return writeState(); }`
2. As mentioned, this pattern is fine if it makes sense for your application.

For your enhancement questions:
1. Absolutely. Improving the state system is something on the radar but it's not necessarily clear to me the best way to support all the different use cases people have, from writing full records, to partial, to event sourcing etc. 
If you have any ideas around this I'd love to hear them.

Hopefully that helps.

**Comment by i3oi3o** [comment]
My current work contract takes away my creator's right under copyright law.
I will contribute to Orbit project in the future.
