### ISSUE TITLE
New shutdown hook possibly allows multiple activation for a short window

### ISSUE THREAD

**Issue by maalikat** [orbit/orbit#301]
When the property orbit.actors.enableShutdownHook is set to true, there are multiple activations for the same actor during a short window when the application restarts under load

**Comment by JoeHegarty** [comment]
I've been able to confirm this can happen and I'm currently evaluating how we might resolve this.

**Comment by JoeHegarty** [comment]
This issue is serious as it violates the "one actor per identity" guarantee in some scenarios (primarily deploys and restarts) that Orbit is meant to give you.
As such, as we have decided to disable this feature in Orbit 1.9.3.

We are working on a fix that will be included in a future Orbit update.

**Comment by JoeHegarty** [comment]
This will be resolved in Orbit 2.0
