### ISSUE TITLE
Have you considered apache ignite.

### ISSUE THREAD

**Issue by alex4o** [orbit/orbit#408]
As I see you are going to rewrite orbit, I was thinking that [Apache Ignite](https://ignite.apache.org/) would be a good replacement for Redis, and it might be worth it to take a look at the project.

**Comment by JoeHegarty** [comment]
Our goal with Orbit 2 is to allow you to bring your own tech, and that includes what to use for the persistent storage. As such, we're open to different options and Apache Ignite may be a good fit.

Right now we're focused on providing a Redis implementation because that's what most users of Orbit today use, but we are also exploring etcd and other options as well for the future.

We also intend to allow people to easily write plugins for their own preferred tech option if we don't provide it.
