### ISSUE TITLE
Documentation lacking

### ISSUE THREAD

**Issue by emansom** [orbit/orbit#413]
I'd like to tryout the 2.0 branch. Is there any documentation, or examples?

**Comment by JoeHegarty** [comment]
Thanks for your interest. Unfortunately Orbit 2 is not yet in a working state, we're working hard to get it there and expect to have an early release in the next few weeks. 
Documentation will accompany the release.

**Comment by emansom** [comment]
Thanks. I'm looking forward to it!
Keep the good work up :slightly_smiling_face:

**Comment by leonlee** [comment]
Orbit is really interesting, Any design concept ?

**Comment by pak3nuh** [comment]
Since this is relative to the lack of documentation, what can we expect from Orbit 2.0?

Will it introduce some fundamental changes or is it just a rewrite in Kotlin to take advantage of features like suspending functions?

Sorry for the hijack.

**Comment by JoeHegarty** [comment]
My apologies on the continuing lack of docs.
It is high on my priority list but other things continue to get in the way.

Orbit 2 is actually quite different to Orbit 1. 

* It's a standalone application - Like a database or similar, you deploy instances of Orbit 2 (or use a managed service in theory)
* More generic - Orbit 2 is not specifically an actor framework but is a more generic routing, placement and messaging platform
* Model what you want - With the above, you can model different kinds of behaviors, from basic RPC to actors and streams. We provide default impls (such as virtual actors) in our client sdks to help you get started
* Standards are good - We've made the tech less custom by leveraging technology such as gRPC under the hood
* Polyglot - Because 2 Orbit is using industry accepted protocols etc, in theory it can work across languages by way of client SDKs. Currently we only have the Kotlin/JVM SDK but there is no reason we couldn't provide Go, NodeJS etc in future
* Modern - For the server side of things we've adopted Kotlin and in general the approach is more modern. We learned a lot of lessons from Orbit 1 and now we have a chance to address them in the core design

There is so much more it is hard to cover, how it does all of the above is quite interesting and I hope to be able to dive deep in the docs to describe it all.

In general, the takeaways are:
* Orbit is effectively a server/service that you access via a client sdk
*  It's meant to help you with the problems inherent in how you place instances of objects, load balance between them and route messages to them in a distributed system
* We've pre-modelled some common use cases (such as virtual actors) to make it as friendly as possible.

**Comment by azell** [comment]
Hoping to learn more about the internal design and decisions made in the near future.

**Comment by wanton7** [comment]
If understood explanation correctly Orbit 2 is somewhat similar to Microsoft's new project called Dapr? Dapr uses sidecar app made with Go language that is running side by side with your client app you can write in any programming language and sidecar handles cluster management, virtual actor routing and storage etc. https://github.com/dapr/dapr

**Comment by brettmorien** [comment]
Hi folks. We've done an initial round of documentation to help with the concepts and onboarding.
[Orbit Docs](http://orbit.github.io/orbit)
There is also a sample app which can help fill in some blanks and get you going.
[Orbit Sample](https://github.com/orbit/orbit-sample)

Hope that's helpful and we can get some time to beef up the docs in the future. We welcome any feedback and we also take contributions, including documentation, if you have them.

**Comment by mattdkerr** [comment]
Looks great!

**Comment by mattdkerr** [comment]
> If understood explanation correctly Orbit 2 is somewhat similar to Microsoft's new project called Dapr? Dapr uses sidecar app made with Go language that is running side by side with your client app you can write in any programming language and sidecar handles cluster management, virtual actor routing and storage etc. https://github.com/dapr/dapr

There are definitely similarities, which is interesting!
